In [4]:
import numpy as np
import skimage as ski


In [3]:
class W:
    def __init__(self):
        self.x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

    def __getitem__(self, item):
        return self.x[item]

w = W()

w[:, 1]

array([2, 5, 8])

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.concatenate((a, a.T))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
np.mgrid[0:2, 0:2]

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[1:2,1:2]

array([[5]])